### ISSUE TITLE
柱状图中的文字显示模糊并且数据少时出现如图情况

### ISSUE THREAD

**Issue by xhm121** [China131/JHChart#13]
![bug](https://cloud.githubusercontent.com/assets/3050188/21339236/7dc9f5ec-c6b8-11e6-986f-2357a6179820.jpeg)

**Comment by China131** [comment]
1.0.3版本已经解决了字体模糊问题，而且由于柱状图的Y轴数值是根据数据源最大的数值决定，如果你的柱状图值最大和最小差距过大，会有几乎看不到柱状图高度的情况。（一般来说，柱状图数值虽然会参差不齐，但是差距不会过大）

**Comment by xhm121** [comment]
字体模糊问题我自己已经解决了，但是文字显示真的有问题，数据小的时候，还是文字显示的位置还是有问题的。楼主有空你可以去改一下，让后人用的时候更好一点，我现在在自己改你的代码。不过还是要谢谢楼主。👍

**Comment by China131** [comment]
好的，我再仔细看看，谢谢反馈哈
