### ISSUE TITLE
推荐给同事用，听同事说，折线图是不能左右滑动的，X轴值太多的时候会显得很密集

### ISSUE THREAD

**Issue by hongdong** [China131/JHChart#14]
推荐给同事用，听同事说，折线图是不能左右滑动的，X轴值太多的时候会显得很密集

**Comment by China131** [comment]
左右滑动问题可以将折线图直接加到一个UISCrollView上面，这样就可以避免显示密集问题了。显示密集问题也会在最近修复，但由于最近有点忙，所以一直没有修改
