### ISSUE TITLE
JHColumnChart  375行出现一个bug    

### ISSUE THREAD

**Issue by chengkaizone** [China131/JHChart#24]
如下代码:
itemsView.backgroundColor = (UIColor *)(_columnBGcolorsArr.count<arr.count?[UIColor greenColor]:_columnBGcolorsArr[j]);

_columnBGcolorsArr是一个多重颜色数组, 这句代码在Objective-C工程中运行正常, 但是在Swift项目中会闪退
_columnBGcolorsArr[j] 得到的值是一个颜色数组[UIColor], 不能直接转化为UIColor

项目很好, 支持你

谢谢!

**Comment by China131** [comment]
_columnBGcolorsArr这个数组存的就是一个颜色数组，我的.h文件中声明错误，十分抱歉，已更正，下一版会纠正😁
