### ISSUE TITLE
第一和第四象限折线图不可左右滚动，数据量多的时候数据会重叠。

### ISSUE THREAD

**Issue by kinglee0120** [China131/JHChart#29]
第一和第四象限折线图不可左右滚动，数据量多的时候数据会重叠。

**Comment by China131** [comment]
滚动问题可以自己将折线图添加在UISCrollView对象上 数据量多的话可以将点的坐标移除掉 x轴坐标调整文字方向

**Comment by China131** [comment]
1.2.0版本X轴刻度值可以纵向显示了，解决了数量多数据重叠的问题
