### ISSUE TITLE
柱状图，柱子上显示的值不能显示全

### ISSUE THREAD

**Issue by firenessZX** [China131/JHChart#34]
请看最高的柱子上显示的值，没有显示全
![img_0079](https://user-images.githubusercontent.com/15721984/28613119-03caf594-7224-11e7-86f5-6b58fe385c27.PNG)

**Comment by China131** [comment]
该bug已修复 请拉下最新分支代码 对contentInsets的top字段操作，即可解决该问题。谢谢反馈
