### ISSUE TITLE
负数的情况下绘制错误

### ISSUE THREAD

**Issue by heyunqian** [China131/JHChart#39]
![0fbbc1c0-132a-4b22-ba1a-f0b3821bdd6f](https://user-images.githubusercontent.com/9826191/29453322-c5bb1976-843b-11e7-8c65-a2ea6386cece.png)

需要双Y轴显示数据；用"折线图-第一象限"绘图的时候，如果数据有负数，折线的位置错误。

**Comment by China131** [comment]
折线图-第一象限 即表示y值无负数，如果y值存在负数 请使用一四象限折线图

**Comment by heyunqian** [comment]
使用一四象限的话不能显示双Y轴吧。如果想像第一象限使用双Y轴，然后显示负数，这样子第一四象限能满足吗？
