### ISSUE TITLE
表格图colWidthArr设置无效

### ISSUE THREAD

**Issue by MichaelChai** [China131/JHChart#41]
创建表格使用colWidthArr设置宽度时，例如三列，table.colWidthArr = @[@30,@130,@50]，前两列有效，最后一列宽度设置无效

**Comment by China131** [comment]
我的本意就是这样 如果你的table宽度设置的不对  我要保证前几列是正常的，最后一列是我用整个table的宽度-前几列宽度获取的。如果你设置的宽度正常(我计算出来的值=你设置的最后一列值)就会正常显示。
