### ISSUE TITLE
第一象限折线图X轴显示过多信息出现显示混乱

### ISSUE THREAD

**Issue by thank1992you** [China131/JHChart#7]
xLineDataArr这个数组赋值从1-31，显示从13开始，会变的特别的挤

**Comment by China131** [comment]
那是因为frame太小了吧？

**Comment by thank1992you** [comment]
确实，是因为frame太小了，是界面的问题，另外我想能不能不要动画，直接显示结果呢 ？

**Comment by China131** [comment]
这个需要做一下调整 如果可以的话  你可以在源码中将路径绘制的动画移除掉，如果你找不到源码 近期我可能会添加这个需求
